#!/usr/bin/env bash
set -euf -o pipefail

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  if [[ $SOURCE != /* ]]; then
    SOURCE="$DIR/$SOURCE"
  fi
done
SCRIPT_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

function dpose() {
    docker-compose --project-name dapper -f "$SCRIPT_DIR/docker-compose.yml" "$@"
}

function usage() {
    echo "Dapper"
    echo "Docker contained applications"
    echo
    echo "Usage:"
    echo "  $ $0 <APP_NAME> [APP_PARAMS...]"
    echo
    echo "Apps:"
    cat "$SCRIPT_DIR/docker-compose.yml" | grep -Eo "^  [a-zA-Z-]+:" | grep -Eo "[a-Z-]+"
    echo
}

function build() {
    echo "Building all apps as APP_NAME parameter was not given"
    dpose build
}

if [ "$#" -lt 1 ]; then
  build
  echo
  usage
else
  dpose run --rm "$@"
fi
