FROM node:10

USER node
RUN mkdir /home/node/.npm-global
ENV PATH=/home/node/.npm-global/bin:$PATH
ENV NPM_CONFIG_PREFIX=/home/node/.npm-global

RUN npm i -g dockerfile-language-server-nodejs

USER root
ENTRYPOINT docker-langserver --stdio
