version: '3.2'

services:

  cadquery:
    image: dcowden/cadquery:latest
    volumes:
      - "$PWD:/home/cq"

  lsp-php:
    image: felixfbecker/php-language-server:latest
    volumes:
      - "$HOME:$HOME"
    command: --stdin

  lsp-bash:
    build:
      context: .
      dockerfile: Dockerfile.lsp-bash
    volumes:
      - "$HOME:$HOME"

  lsp-dockerfile:
    build:
      context: .
      dockerfile: Dockerfile.lsp-dockerfile
    volumes:
      - "$HOME:$HOME"

  lsp-dart:
    build:
      context: .
      dockerfile: Dockerfile.lsp-dart
    volumes:
      - "$HOME:$HOME"

  kafkacat:
    image: confluentinc/cp-kafkacat:latest
    network_mode: host
    working_dir: /tmp/pwd
    volumes:
      - .:/tmp/pwd
    entrypoint:
      - /usr/local/bin/kafkacat
    command: "-b ${KAFKACAT_TARGET:-kafka} -L"
